// 기존에 쓰시던 US report 자동완성 사전을 그대로 옮겨왔습니다.
// {{cursor}} 는 자동완성 삽입 후 커서가 위치할 지점을 뜻합니다.
export const US_DICT: Record<string, string> = {
  indication: "indication",
  diffuse: "diffuse",
  increased: "increased",
  decreased: "decreased",
  vascularity: "vascularity",
  heterogeneous: "heterogeneous",
  homogeneous: "homogeneous",
  hypoechoic: "hypoechoic",
  hyperechoic: "hyperechoic",
  echogenicity: "echogenicity",
  isoechoic: "isoechoic",
  multiple: "multiple",
  thyroid: "thyroid",
  isthmus: "isthmus",
  thickness: "thickness",
  level: "level",
  lv: "level",
  right: "right",
  rt: "right",
  left: "left",
  lt: "left",
  normal: "normal",
  abnormal: "abnormal",
  colloid: "colloid",
  solid: "solid",
  cystic: "cystic",
  spongiform: "spongiform",
  extrathyroidal: "extrathyroidal extension",
  upper: "upper",
  lower: "lower",
  nodule: "nodule",
  predominantly: "predominantly",
  partially: "partially",
  bilateral: "bilateral",
  volume: "volume",
  pure: "pure",
  punctate: "punctate echogenic foci (+)",
  taller: "taller than wide",
  nonparallel: "nonparallel orientation",
  irregular: "irregular",
  spiculate: "spiculate",
  comet: "comet-tail artifact",
  paraisthmic: "paraisthmic",
  rim: "rim calcification (+)",
  suspicious: "suspicious",
  lymph: "lymph node",
  negative: "negative",
  size: "size: ",
  thyroiditis: "thyroiditis",
  preserved: "preserved",
  markedly: "markedly",
  new: "newly detected lesion",
  interval: "no significant interval change",
  features: "features",
  noevidence: "no evidence of",
  corresponding: "corresponding to patient's palpable mass",
  unremarkable: "otherwise, unremarkable findings",
  thyroidnl: "Normal size and echogenicity of both thyroid glands without focal solid or cystic nodules.",
  postop: "No evidence of local tumor recurrence or abnormal lymph node in the operative bed.",
  bed: "operative bed",
  remnant: "remnant thyroid gland",
  reactive: "suggestive of reactive lymphadenopathy",
  suspiciousln: "suspicious metastatic lymph node",
  hilum: "loss of echogenic fatty hilum",
  ln0: "No enlarged lymph nodes",
  lnben:
    "Enlarged lymph nodes in the neck level {{cursor}}\n- size: \n- ovoid shape with preserved fatty hilum\n- no definite abnormal vascularity",
  lnsus:
    "Enlarged lymph nodes in neck level {{cursor}}\n- size: \n- round to oval shape\n- fatty hilum not clearly identified\n- heterogeneous echogenicity",
  lnmax: "- largest lymph node at {{cursor}}, size:",
  focalt: "possible focal thyroiditis, however thyroid nodule cannot be excluded",
  nsf: "Diffuse thyroid disease\n- heterogeneous echogenicity\n- within normal range of volume",
  graves: "diffuse hypoechogenicity\n- markedly increased vascularity\n- diffuse enlargement",
  kt2: "benign (K-TIRADS 2)",
  kt3: "low suspicion (K-TIRADS 3)",
  kt4: "intermediate suspicion (K-TIRADS 4)",
  kt5: "high suspicion (K-TIRADS 5)",
  nsfsalivary: "No abnormal findings in the parotid and submandibular glands",
  scm: "sternocleidomastoid muscle",
  strap: "strap muscle",
  smg: "submandibular gland",
  fnac: "US-guided FNAC from the {{cursor}}\n- No immediate complication",
};
